---
- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
  - name: Wait for all hosts to respond
    wait_for_connection:
      timeout: 120

- hosts: all
  become: yes
  become_user: root
  strategy: free
  roles:
    - common-step1

- hosts: workstations
  become: yes
  become_user: root
  strategy: free
  roles:
    - workstation

- hosts: servera
  become: yes
  become_user: root
  strategy: free
  roles:
    - certauthority
    - dnsserver
    - ldapserver
    - krbserver

- hosts: all
  become: yes
  become_user: root
  strategy: free
  roles:
    - common-step2

