---
- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
  - name: Wait for all hosts to respond
    wait_for_connection:
      timeout: 300
  - name: Ensure that firewalld is enabled and started
    service:
      name: firewalld.service
      state: started
      enabled: yes

- hosts: gateway
  become: yes
  become_user: root
  strategy: free
  roles:
    - gateway

- hosts: all
  become: yes
  become_user: root
  strategy: free
  roles:
    - common-step1

- hosts: workstations
  become: yes
  become_user: root
  strategy: free
  roles:
    - workstation

- hosts: servera
  become: yes
  become_user: root
  strategy: free
  roles:
    - certauthority
    - dnsserver
    - ldapserver
    - krbserver

- hosts: all
  become: yes
  become_user: root
  roles:
    - common-step2

