---
- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
  - name: wait for all hosts to respond
    wait_for_connection:
      timeout: 120

- hosts: all
  become: yes
  become_user: root
  strategy: free
  roles:
    - common

- hosts: workstations
  become: yes
  become_user: root
  strategy: free
  roles:
    - workstation

- hosts: servera
  become: yes
  become_user: root
  strategy: free
  roles:
    - dnsserver
