---
- name: Install GUI environment
  yum:
    name: "@graphical-server-environment,@gnome-desktop,@gnome-apps,@graphical-admin-tools"
    state: present
  notify:
  - Restart workstations
- name: Set default target to Graphical
  file:
    path: /etc/systemd/system/default.target
    state: link
    src: /lib/systemd/system/graphical.target
  notify:
  - Restart workstations

