---
- name: restart DNS server
  service:
    name: named-chroot-setup
    state: restarted
  changed_when: yes
  notify: restart DNS server step 2
- name: restart DNS server step 2
  service:
    name: named-chroot
    state: restarted

