---
- name: Restart KDC service
  service:
    name: krb5kdc.service
    state: restarted
- name: Restart KADMIN service
  service:
    name: kadmin.service
    state: restarted
- name: Restart OpenLDAP service
  service:
    name: slapd.service
    state: restarted
- name: Restart saslauthd service
  service:
    name: saslauthd.service
    state: restarted
- name: Reload systemd configuration
  systemd:
    daemon_reload: yes

