---
- name: Set keyboard layout to US-ACENTOS
  command:
    argv:
    - /usr/bin/localectl
    - set-keymap
    - us-acentos
- name: Create CDROM mount point
  file:
    path: "{{ CDROMISOMountPoint }}"
    state: directory
- name: Mount the ISO image on CDROM mount point
  mount:
    src: "{{ CDROMDevice }}"
    path: "{{ CDROMISOMountPoint }}"
    fstype: auto
    opts: defaults,x-systemd.automount,nofail
    state: mounted
    boot: yes
- name: Disable stock YUM repositories
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: "{{ item }}"
    option: enabled
    value: "0"
    no_extra_spaces: yes
  with_items:
  - base
  - updates
  - extras
  - centosplus
- name: Enable local YUM repository
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Media.repo
    section: "c7-media"
    option: enabled
    value: "1"
    no_extra_spaces: yes
- name: Install Kerberos client packages
  yum:
    name: "krb5-workstation"
    state: present
- name: Deploy krb5.conf file
  template:
    dest: "/etc/krb5.conf.d/{{ example_dns_name }}.krb5.conf"
    force: yes
    group: root
    mode: "0644"
    owner: root
    src: krb5.conf.j2
- name: Load variables from LDAP role main file
  include_vars: roles/ldapserver/vars/main.yml
- name: Install OpenLDAP client packages
  yum:
    name: "openldap,openldap-clients"
    state: present
- name: Install SASL client packages
  yum:
    name: "cyrus-sasl-gssapi,cyrus-sasl-plain"
    state: present
- name: Deploy ldap.conf file
  template:
    src: ldap.conf.j2
    dest: /etc/openldap/ldap.conf
    force: yes
    group: root
    mode: "0644"

