---
- name: disable stock YUM repositories
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: "{{ item }}"
    option: enabled
    value: "0"
  with_items:
    - base
    - updates
    - extras
    - centosplus
- name: enable local YUM repository
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Media.repo
    section: "c7-media"
    option: enabled
    value: "1"

