---
- name: Set keyboard layout to US-ACENTOS
  command:
    argv:
    - /usr/bin/localectl
    - set-keymap
    - us-acentos
# https://access.redhat.com/solutions/1434943
- name: Increase maximum number of processes
  sysctl:
    name: "kernel.pid_max"
    value: "131072"
    sysctl_file: "/etc/sysctl.d/{{ example_dns_name }}.conf"
- name: Create CDROM mount point
  file:
    path: "{{ CDROMISOMountPoint }}"
    state: directory
- name: Mount the ISO image on CDROM mount point
  mount:
    src: "{{ CDROMDevice }}"
    path: "{{ CDROMISOMountPoint }}"
    fstype: auto
    opts: defaults,x-systemd.automount,nofail
    state: mounted
    boot: yes
- name: Disable stock YUM repositories
  ini_file:
    dest: "/etc/yum.repos.d/CentOS-{{ item.file }}.repo"
    section: "{{ item.section }}"
    option: enabled
    value: "0"
    create: no
    no_extra_spaces: yes
  ignore_errors: yes
  with_items:
  - file: Stream-BaseOS
    section: baseos
  - file: Stream-Extras
    section: extras
  - file: Stream-AppStream
    section: appstream
  - file: Base
    section: base
  - file: Base
    section: updates
  - file: Base
    section: extras
  - file: Base
    section: centosplus
- name: Enable local YUM repository
  ini_file:
    dest: /etc/yum.repos.d/CentOS-{{ item.file }}.repo
    section: "{{ item.section }}"
    option: enabled
    value: "1"
    create: no
    no_extra_spaces: yes
  ignore_errors: yes
  with_items:
  - file: Stream-Media
    section: media-baseos
  - file: Stream-Media
    section: media-appstream
  - file: Media
    section: c7-media
- name: Install Kerberos client packages
  yum:
    name: "krb5-workstation"
    state: present
- name: Deploy krb5.conf file
  template:
    dest: "/etc/krb5.conf.d/{{ example_dns_name }}.krb5.conf"
    force: yes
    group: root
    mode: "0644"
    owner: root
    src: krb5.conf.j2
- name: Load variables from LDAP role main file
  include_vars: roles/ldapserver/vars/main.yml
- name: Install OpenLDAP client packages
  yum:
    name: "openldap,openldap-clients"
    state: present
- name: Install SASL client packages
  yum:
    name: "cyrus-sasl-gssapi,cyrus-sasl-plain"
    state: present
- name: Deploy ldap.conf file
  template:
    src: ldap.conf.j2
    dest: /etc/openldap/ldap.conf
    force: yes
    group: root
    mode: "0644"

