---
- name: Check whether DKMS is installed and running
  block:
  - name: Enable and start DKMS service
    service:
      name: dkms.service
      state: started
      enabled: true
  rescue:
  - name: Reenable stock YUM repositories temporarily
    ini_file:
      dest: /etc/yum.repos.d/CentOS-Base.repo
      section: "{{ item }}"
      option: enabled
      value: "1"
    with_items:
      - base
      - updates
      - extras
      - centosplus
  - name: Install EPEL-release and DeltaRPM
    yum:
      name: "epel-release"
      state: present
  - name: Install DeltaRPM and DKMS
    yum:
      name: "deltarpm,dkms"
      state: present
  - name: Enable and run DKMS service
    service:
      name: dkms.service
      state: started
      enabled: true
  - name: Disable stock YUM repositories again
    ini_file:
      dest: /etc/yum.repos.d/CentOS-Base.repo
      section: "{{ item }}"
      option: enabled
      value: "0"
    with_items:
      - base
      - updates
      - extras
      - centosplus
  - name: Disable EPEL repositories
    ini_file:
      dest: /etc/yum.repos.d/epel.repo
      section: epel
      option: enabled
      value: "0"
  - name: Update MAN database
    command:
      argv: /etc/cron.daily/man-db.cron
    register: mandbcron_output
    changed_when: false
    failed_when: mandbcron_output.rc != 0

