---
- name: check whether DMKS is installed and running
  block:
    - service:
        name: dkms.service
        state: started
        enabled: true
  rescue:
    - name: reenable stock YUM repositories temporarily
      ini_file:
        dest: /etc/yum.repos.d/CentOS-Base.repo
        section: "{{ item }}"
        option: enabled
        value: "1"
      with_items:
        - base
        - updates
        - extras
        - centosplus
    - name: install EPEL-release and DeltaRPM
      yum:
        name: "epel-release"
        state: present
    - name: install DeltaRPM and DKMS
      yum:
        name: "deltarpm,dkms"
        state: present
    - name: enable and run DKMS service
      service:
        name: dkms.service
        state: started
        enabled: true
    - name: disable stock YUM repositories again
      ini_file:
        dest: /etc/yum.repos.d/CentOS-Base.repo
        section: "{{ item }}"
        option: enabled
        value: "0"
      with_items:
        - base
        - updates
        - extras
        - centosplus
    - name: disable EPEL repositories
      ini_file:
        dest: /etc/yum.repos.d/epel.repo
        section: epel
        option: enabled
        value: "0"

